name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Clone Serum Analyzer
      uses: actions/checkout@v2
      with:
        repository: serum-errors/go-serum-analyzer
        ref: master
        path: go-serum-analyzer
    - name: Install Serum Analyzer
      working-directory: go-serum-analyzer
      run: go install ./cmd/go-serum-analyzer/
    - name: Run Serum Analyzer
      run: go-serum-analyzer ./...
    - name: Run Tests
      run: go test ./...
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - run: mkdir /tmp/bundle
    - run: cp plugins/* /tmp/bundle
    - name: Build warpforge binary
      run: go build -o /tmp/bundle/warpforge cmd/warpforge/*
    - name: Create release tarball
      run: tar -C /tmp/bundle/ -czvf warpforge.tgz .
    - name: Archive release tarball
      uses: actions/upload-artifact@v2
      with:
        name: warpforge.tgz
        path: warpforge.tgz