name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    
    - name: Build warpforge binary
      run: mkdir /tmp/bundle
      run: go build -o /tmp/bundle/warpforge cmd/warpforge/*

    - name: Create release tarball
      run: cp plugins/* /tmp/bundle
      run: tar -C /tmp/bundle/ -czvf warpforge.tgz .

    - name: Archive release tarball
      uses: actions/upload-artifact@v2
      with: 
        name: warpforge.tgz
        path: /tmp/bundle/warpforge.tgz


  

