name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    
    - name: Setup Workspace
      run: |
        ./setup-test-workspace.sh
    
    - name: Run Tests
      run: go test ./...